name = "ogallala-subscriber-portal"
main = "src/index.js"
compatibility_date = "2026-09-10"
workers_dev = true

[vars]
STRIPE_PRICE_ID = "price_1UDtXDAhqvqGsdlQGboki05S"

[observability]
enabled = true
